{
  customSyntax: 'postcss-scss',
  extends: 'stylelint-config-standard',
  plugins: [
    'stylelint-selector-bem-pattern',
    'stylelint-scss',
    'stylelint-order',
    "stylelint-high-performance-animation",
    "@namics/stylelint-bem"
  ],
  rules: {
    # desligado para permitir !default
    # TODO: ver porque essa regra está ligada
    # https://stylelint.io/user-guide/rules/annotation-no-unknown/
    'annotation-no-unknown': null,

    # desligado para permitir @use @forward e outros
    # TODO: descobrir porque essa configuração não vem no stylelint-scss
    # https://stylelint.io/user-guide/rules/at-rule-no-unknown/
    'at-rule-no-unknown': null,

    'at-rule-no-vendor-prefix': true,
    'block-closing-brace-newline-after': 'always',
    'block-closing-brace-newline-before': 'always',
    'block-no-empty': true,
    'block-opening-brace-newline-after': 'always',
    'block-opening-brace-space-before': 'always',
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'color-no-invalid-hex': true,
    'comment-no-empty': true,
    'declaration-bang-space-before': 'always',
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-redundant-longhand-properties': true,
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-block-single-line-max-declarations': 1,
    'declaration-colon-space-after': 'always-single-line',
    'declaration-colon-newline-after': 'always-multi-line',
    'declaration-no-important': true,
    'function-calc-no-unspaced-operator': true,
    'function-name-case': 'lower',

    # desligado para poder utilizar as funções SCSS list.append, string.slide...
    # TODO: ver porque essa regra está ligada
    # https://stylelint.io/user-guide/rules/function-no-unknown/
    'function-no-unknown': null,

    indentation: 2,

    # permite ter 2 seletores do keyframe com o mesmo valor
    # útil por exemplo para 25%-50% 50%-100% onde o 50% se repete
    # https://stylelint.io/user-guide/rules/keyframe-block-no-duplicate-selectors/
    'keyframe-block-no-duplicate-selectors': null,

    'keyframe-declaration-no-important': true,
    'length-zero-no-unit': true,
    'max-nesting-depth': 6,
    'media-feature-name-case': 'lower',
    'media-feature-name-no-unknown': true,
    'media-feature-name-no-vendor-prefix': true,
    'no-irregular-whitespace': true,
    'number-max-precision': 2,
    'number-no-trailing-zeros': true,
    'order/properties-alphabetical-order': true,
    'property-case': 'lower',
    'property-no-unknown': true,
    'property-no-vendor-prefix': true,

    # desligado pois conflita com o padrão BEM
    # https://stylelint.io/user-guide/rules/selector-class-pattern/
    'selector-class-pattern': null,

    'string-quotes': 'single',
    'plugin/selector-bem-pattern': { preset: 'bem', presetOptions: { namespace: 'houf' } },
    'property-disallowed-list': [ 'float', 'clear' ],
    'max-line-length': [ 100, { ignore: [ 'comments' ] } ],
    'selector-descendant-combinator-no-non-space': true,
    'selector-no-qualifying-type': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-class-case': 'lower',
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-case': 'lower',
    'selector-pseudo-element-no-unknown': [ true, { ignorePseudoElements: [ 'input-placeholder' ] } ],
    'selector-type-no-unknown': [ true, { ignore: [ 'custom-elements', 'default-namespace' ] } ],
    # 'scss/at-import-no-partial-leading-underscore': true,
    # 'scss/at-import-partial-extension': 'never',
    'scss/at-rule-no-unknown': true,
    'scss/selector-no-redundant-nesting-selector': true,
    'shorthand-property-no-redundant-values': true,
    'string-no-newline': true,
    'value-no-vendor-prefix': true,
    "plugin/no-low-performance-animation-properties": [
      true,
      {
        "ignore": "paint-properties"
      }
    ]
  }
}