name: Delete link temp preview

on:
  delete:
    branches:
      - 'feat*'
      - 'fix*'
      - 'docs*'
      - 'release*'

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete temp Preview
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: tmp/${{ github.ref_name }}/**
          keep_files: true

