name: Feature

on:
  push:
    branches:
      - 'feat*'
      - 'fix*'
      - 'docs*'
      - 'release*'

  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint && npm run stylelint

      - name: Build
        run: npm run build

      - name: Docs
        run: npm run docs

      - name: Deploy temp Preview
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/preview
          destination_dir: tmp/${{ github.ref_name }}
          keep_files: true

