name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint && npm run stylelint

      - name: Build
        run: npm run build

      - name: Docs
        run: npm run docs

      - name: Set up Git user
        run: |
          git config --global user.name "CI/CD Bot"
          git config --global user.email "ci-bot@example.com"

      - name: Release
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Deploy temp Preview
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/preview
          keep_files: true

